# Config file for travis-ci.org

language: php
php:
  - "nightly"
  - "8.0"
  - "7.4"
  - "7.3"
  - "7.2"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
matrix:
  allow_failures:
    - php: ["nightly", "8.0"]
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script: cd _test && ./phpunit.phar --stderr --group plugin_structsection
