name: PHP Code Style

on: pull_request

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.2'
                  tools: cs2pr, phpcs

            - name: retrieve script
              run: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

            - name: print current directory contents
              run: ls

            - name: Install DokuWiki
              env:
                  CI_SERVER: 1
                  DOKUWIKI : master
              run: sh travis.sh

            - name: print current directory contents
              run: ls

            - name: run PHP codesniffer
              run: phpcs -q --standard=_test/phpcs.xml --report=checkstyle lib/plugins/structsection
                  | sed 's/dokuwiki\/lib\/plugins\//dokuwiki-plugin-/'
                  | cs2pr
