name: PHP Code Style

on:
    push:
    pull_request:
        branches:
            - '**:**'

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.2'
                  tools: cs2pr, phpcs

            - name: retrieve script
              run: wget https://raw.githubusercontent.com/splitbrain/dokuwiki/master/_test/phpcs.xml

            - name: run PHP codesniffer
              run: phpcs -q --standard=phpcs.xml --report=checkstyle . | cs2pr
